language: php
sudo: required
services:
    - docker

before_install:
    - docker-compose up -d
    - docker exec -it payments-ddd-es-tutorial-php composer install

script:
    - docker exec -it payments-ddd-es-tutorial-php vendor/bin/phpunit -c phpunit.xml.dist

