version: '2'

services:
    php:
        build:
            context: ./
            dockerfile: Dockerfile.dev
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        links:
          - mongo
    mongo:
        image: mongo:latest
